Refactor robot-simulator exercise
artamonovkirill/groovy pull request #1
Opened 2024-10-15 07:38 UTC by artamonovkirill

- verify results properties through getters
- make code groovier (use def key-word, remove semi-colons)
- use Spock's given/when/then
- visually separate parts of data-driven test inputs

2024-10-15 07:38 UTC, artamonovkirill commented on exercises/practice/robot-simulator/.meta/src/reference/groovy/RobotSimulator.groovy
> +    def getX() {
given `getX` method is defined, groovy uses it in the code like `robot.x`

2024-10-15 07:41 UTC, artamonovkirill commented on exercises/practice/robot-simulator/.meta/src/reference/groovy/RobotSimulator.groovy
> +    String getDirection() {
By using getters, we let internal implementation use any other type to store direction (I opted for int in my solution)

2024-10-15 07:42 UTC, artamonovkirill commented on exercises/practice/robot-simulator/.meta/src/reference/groovy/RobotSimulator.groovy
> -        this.pos_x = pos_x;
semi-colon are not required in Groovy

2024-10-15 07:42 UTC, artamonovkirill commented on exercises/practice/robot-simulator/src/test/groovy/RobotSimulatorSpec.groovy
> +        when:
given/when/then to have more readable tests

2024-10-15 07:43 UTC, artamonovkirill commented on exercises/practice/robot-simulator/src/test/groovy/RobotSimulatorSpec.groovy
> +        label                               || x  | y  | direction
| works as a separator as well, left || only to separate distinct parts of data-driven tests input

2024-10-15 09:46 UTC, artamonovkirill commented on exercises/practice/robot-simulator/src/main/groovy/RobotSimulator.groovy
> +    String getDirection() {
By using getters, we let internal implementation use any other type to store direction (I opted for int in my solution)

2024-10-15 09:50 UTC, artamonovkirill commented on exercises/practice/robot-simulator/src/main/groovy/RobotSimulator.groovy
> +    int getX() {
If `getX()` is defined, Groovy will use the getter in code like `results.x`.
I'm fine with defining simply `x()`, `y()` and `direction()` getters to minimize Groovy features in the context of the exercise

2024-10-15 13:02 UTC, glennj requested changes
I'm in favour of all of this. But a quick bit of instruction to new users is wanted here.

2024-10-19 09:29 UTC, artamonovkirill commented
> I'm in favour of all of this. But a quick bit of instruction to new users is wanted here.

Added a note here: https://github.com/artamonovkirill/groovy/pull/1/commits/3a8737ee09c376e1ad545d3f274ec61a471b8ad8#diff-8639b57aa8e48068d53e221629cc931542d14f2b0e464bfd429316d722c0806f
Would that be sufficient or should I also go into explaining what getters and setters are?

2024-10-21 18:08 UTC, glennj commented
> Added a note here: [3a8737e](https://github.com/artamonovkirill/groovy/commit/3a8737ee09c376e1ad545d3f274ec61a471b8ad8) Would that be sufficient or should I also go into explaining what getters and setters are?

This is great.

The new text must be added to a file named `instructions.append.md` -- if someone were to re-sync the exercise with the problem-specifications repo, the new text would be lost.

The Exercism markdown standards require that every markdown file has exactly one level-one heading, even if that header will be ignored. `instructions.append.md` should start like

```markdown
# ignore

## Properties and fields in Groovy

In this exercise, ...
```

2024-10-22 07:24 UTC, artamonovkirill commented
> The new text must be added to a file named `instructions.append.md` -- if someone were to re-sync the exercise with the problem-specifications repo, the new text would be lost.

Done. As the PR seems to be reaching it's final form, I've also already created one towards the Exercism's repo: https://github.com/exercism/groovy/pull/461

2024-10-23 09:22 UTC, closed without merging